# Configuración básica del sitio
title: CriptoEduAr - Plataforma Interactiva
description: Una plataforma educativa interactiva para aprender sobre criptomonedas, blockchain y finanzas descentralizadas.
baseurl: "" # Ruta base del sitio (deja esto en blanco si no usas subdirectorios)
url: "https://ariasalejo.github.io/CriptoEduAr" # URL del sitio en GitHub Pages

# Tema de Jekyll (opcional)
theme: minima

# Configuración de GitHub Pages
plugins:
  - jekyll-feed # Genera un feed RSS para tu sitio

# Metadatos adicionales
author:
  name: Tu Nombre
  email: tu-email@example.com
  twitter: https://twitter.com/tu-usuario
  github: https://github.com/ariasalejo

# Opciones de navegación
navigation:
  - title: Inicio
    url: /
  - title: Simulador de Portafolio
    url: /#simulador
  - title: Calculadora de Precios
    url: /#calculadora
  - title: Conversor de Criptomonedas
    url: /#conversor
  - title: Noticias Cripto
    url: /#noticias
  - title: Recursos Educativos
    url: /#recursos

# Redes sociales
social_links:
  twitter: https://twitter.com/tu-usuario
  github: https://github.com/ariasalejo
  youtube: https://www.youtube.com/tu-canal

# Configuración de NewsAPI
newsapi:
  api_key: 45b326355e6646eb91a52c48776d369b

# Ajustes de desarrollo
markdown: kramdown
exclude:
  - README.md
  - cobfig.yml
