name: Despliegue en GitHub Pages

on:
  push:
    branches:
      - main # Cambia a "master" si usas esa rama

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0 # Ajusta la versión de Ruby si es necesario

      - name: Instalar dependencias
        run: |
          gem install bundler
          bundle install

      - name: Construir el sitio
        run: bundle exec jekyll build

      - name: Desplegar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site